### ISSUE TITLE
No Installer - Please advise

### ISSUE THREAD

**Issue by lowerider21** [keif888/SQLServerMetadata#16]
Forgive me but I cannot figure out how to install this. I have installed a version from codeplex that has SS 2014 but I am trying to upgrade to this version. I have it opened in Visual Studio but that has been a dead end as far as getting it running.  I cannot locate an exe or msi file. Please advise. Thanks

**Comment by fmms** [comment]
Have a look at https://github.com/keif888/SQLServerMetadata/releases

**Comment by lowerider21** [comment]
Thank you so much. For whatever reason i could not find that. Please mark as resolved.
