### ISSUE TITLE
2017 Error Enumerating Database - Could not load file or assembly

### ISSUE THREAD

**Issue by lowerider21** [keif888/SQLServerMetadata#17]
I am receiving the following error message when trying to scan a SQL Server 2017 (with a 2017 Repo). I have tried this on two machines and I am getting the same error on both (windows 10 machines). The 2014 and 2016 analyzer worked fine. I tried in the GUI and command line and received the error both places. I have SSMS 17.7 installed locally. I googled the error for a while thinking it was my local but than tried on a second machine.
Unexpected error occurred: Could not load file or assembly 'Microsoft.SqlServer.Smo, Version=14.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
Stack Trace:
   at Microsoft.Samples.DependencyAnalyzer.SQLDBEnumerator.EnumerateDatabase(String dbConnection, Boolean storeThreePartNames)
   at Microsoft.Samples.DependencyAnalyzer.Program.EnumerateDatabase(DependencyArguments dependencyArguments, Repository repository)
   at Microsoft.Samples.DependencyAnalyzer.Program.Main(String[] args)

**Comment by keif888** [comment]
Prior to SQL Server 2017 the SMO objects were deployed as part of other installs, or as a separate MSI.  For SQL Server 2017, they were changed to a NuGet package as per https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/installing-smo?view=sql-server-2017. and have to be deployed as part of the software package.  I was unaware of this prior to today.

Release Beta 0.23.0.0 should correct this issue:
https://github.com/keif888/SQLServerMetadata/releases

**Comment by lowerider21** [comment]
I hate to be a pain but that MSI will not execute and install on my machine. It just sits. I restarted a few times, tried installing as Admin, as another user, etc. So far I get nothing. I tried on another machine and it did install there so I am not sure what the issue is. When i tried to enumerate a database though i now get this issue. CLR is installed for 2017 on that machine.
Could not enumerate the database: Could not load file or assembly 'Microsoft.SqlServer.SqlClrProvider, Version=14.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.

**Comment by keif888** [comment]
The MSI is installing without issues on my development and test machines, although SmartScreen is kicking in as it's a new msi file that hasn't been "seen".

I packaged the MSI file with only the DLL's that are referenced in the project, but it appears that some others are being dynamically linked in.  I will add all the DLL's included in the NuGet package to attempt to ensure there are no other issues of the missing DLL type.

**Comment by lowerider21** [comment]
Good news and bad news. The enumerating of the database is now running. However three specific issues.
1) The data from the scan is not being written to the repository database. The object and RunScan tables are blank. No errors showing up to indicate there is an issue. Repo is on a 2017 server.
2) The error below occurred when trying to scan a SSIS 2017 Catalog.
3) When it was scanning .dtproj it would hang on one of my solutions. I have no error message or log, it just hung. It must be something about that particular project cause it was able to scan others. This is more an FYI at this point.
Sorry to bring more bad news.

Error message for issue 2.
Enumerating Integration Services metadata.
Unexpected error occurred: GenericArguments[0], 'Microsoft.SqlServer.Management.IntegrationServices.Catalog', on 'Microsoft.SqlServer.Management.Sdk.Sfc.SfcCollection`3[T,K,ParentT]' violates the constraint of type parameter 'T'.
Stack Trace:
   at Microsoft.Samples.DependencyAnalyzer.SSISEnumerator.EnumerateSqlPackages(String server, String user, String pwd, String[] rootFolders, Boolean storeThreePartNames, String[] storePackagePasswords)
   at Microsoft.Samples.DependencyAnalyzer.Program.EnumerateSSIS(DependencyArguments dependencyArguments, Repository repository)
   at Microsoft.Samples.DependencyAnalyzer.Program.Main(String[] args)

**Comment by keif888** [comment]
I have split the three issues mentioned above out into separate issues, so I can track the fixes against them.
#18, #19, and #20.
Could you please, if possible, upload the solution that causes the hang against #20?
Or maybe just the SSIS package?

**Comment by lowerider21** [comment]
I will look where it failed and what I can upload. I do know there are third party add ins (Pragmatic Works Task Factory) Components in the solution that failed.

**Comment by keif888** [comment]
2 of three issues above have been addressed in latest release.
The data from scan one I am unable to replicate.
Closing this issue, as the others now track them.
