### ISSUE TITLE
The data from the scan is not being written to the repository database.

### ISSUE THREAD

**Issue by keif888** [keif888/SQLServerMetadata#18]
This issue is split from #17 
The data from the scan is not being written to the repository database. The object and RunScan tables are blank. No errors showing up to indicate there is an issue. Repo is on a 2017 server.

**Comment by keif888** [comment]
Unable to replicate.
Tested from Windows 10 client machine with SSDT 15.4 installed and subsequently with SSDT 15.7 installed.
Analysing either SQL Server Db's or SSIS packages on file system are writing to SQL 2017 repository.

**Comment by lowerider21** [comment]
Here is my take on this. The lock up for me was happening in the SSIS packages. Therefore it never completed. It appears the scan waits till the end to write the data to the repo. If it locks up, it never gets to that step. Therefore no data written. I have been able to run the scan with .26 release and it is writing data to the repo on 2017.

**Comment by keif888** [comment]
Closed, as caused by already fixed issue.
