### ISSUE TITLE
Hangs on some SSIS solutions

### ISSUE THREAD

**Issue by keif888** [keif888/SQLServerMetadata#20]
This issue is split from #17.
When it was scanning .dtproj it would hang on one of my solutions. I have no error message or log, it just hung. It must be something about that particular project cause it was able to scan others. This is more an FYI at this point.

**Comment by lowerider21** [comment]
Is there a way to send the file directly to you for testing not share it on here?

**Comment by keif888** [comment]
I have setup an azure blob storage, which is configured with write and list permissions only.
To access it you need Azure Storage Explorer, and the following access key (active for the next 7 days):

`https://sqlmetadata.blob.core.windows.net/issue20?sv=2017-07-29&si=issue20-write&sr=c&sig=XqLCWUMOR%2FIRudl9jrA1EQENv5KedTT3eBAXoN9X%2Brk%3D`

Download the Azure Storage Explorer from [Azure Storage Explorer](https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-manage-with-storage-explorer?tabs=windows)
Then add a storage account Icon looks like a power plug on left.
Select "Use a connection string or shared access signature URI" (next)
Select "Use a SAS URI", and paste the access key into the URI (next)
Then Connect.

You should see a Blob Container called issue20 appear in your local and attached section of the explorer.

To confirm that this is secured, please upload a small text file, and attempt to download or delete it.  The permissions will prevent you from doing so.
Then upload the other files you want to provide to me.

**Comment by lowerider21** [comment]
Uploaded files. Thanks

**Comment by keif888** [comment]
Thanks, write permissions removed.  I will post further updates as I find the underlying issues.

**Comment by keif888** [comment]
Issue may be in the SSISProjectBuilder.exe that is called to construct an ispac file from the dtproj file.
But I am not sure. as I thought I got a hang but I haven't been able to repeat it to find underlying cause.

**Comment by keif888** [comment]
Issue was in the way that the output from SSISProjectBuilder was being accessed, synchronously instead of asynchronously.  Added timeout on execute as well to prevent eternal hang.
Fixed in 0.25.0.0 release.
