### ISSUE TITLE
Store ISPAC filename + analyse timestamp

### ISSUE THREAD

**Issue by fpatou** [keif888/SQLServerMetadata#25]
hello

Would it be possible to store those information into the SSIS_META database ?
ISPAC filename + analyse timestamp.

Regards

**Comment by keif888** [comment]
The ObjectAttrName field with the value PackageLocation, is supposed to be logging the ISPack name.  I have corrected that in the commit listed above.  You will now get the ISPack name, followed by an back slash, and then the package name within the ISPack (as the dtproj files are already handled).
Joining to the RunScan table using the RunKey column will allow the retrieval of the analysis timestamp.

**Comment by fpatou** [comment]
Thank you this will help a lot  !
tested just right now and works sucessfuly
