### ISSUE TITLE
sqlStatement.getTableNames() not returning all tables used if you identify insert statement with nested derived tables

### ISSUE THREAD

**Issue by FrankSagt** [keif888/SQLServerMetadata#36]
Hi @keif888  
When the insert statement is identified, not all tables are returned when a derived-table is used. 
I only get two tables back, instead of 4.

I also took the example of Microsoft, with the same effect. 
Or show the SQL Script in attachment. 
[SQLQuery1.sqlSample Insert Into.txt](https://github.com/keif888/SQLServerMetadata/files/7492521/SQLQuery1.sqlSample.Insert.Into.txt)

[https://docs.microsoft.com/de-de/sql/t-sql/statements/insert-transact-sql?view=sql-server-2017#v-inserting-data-returned-from-an-output-clause](url)

Where is my mistake? Which classes do I have to use to analyze nested derived tables?

Vielen dank für deine Unterstützung .

Viele Grüße Frank Kreß

**Comment by keif888** [comment]
The findIdentifiers(TableReference tableSource) method was not parsing the Merge statement.  This has been fixed in the code base.
