### ISSUE TITLE
no .exe file per wiki documentation

### ISSUE THREAD

**Issue by rgfuller** [keif888/SQLServerMetadata#9]
Hello, there is no .exe file in SQLServerMetadata-master.zip.  Please explain how to install this

**Comment by keif888** [comment]
I am having issues getting the code base to compile in Visual Studio 2017.
This is mainly due to MSAGL, which I use to display the graphics having issues with VS2017.
The most recent version is available here: http://sqlmetadata.codeplex.com/releases/view/621301

**Comment by keif888** [comment]
Wiki updated, and release 20 placed into release area of github.
